# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3de02f2cbf11074a90546fa0fb54a910a849f515be21fcf079d766ffc73de747c2e2542066ffde29c61d55a6c71b01f15a50e4631a2bbd881acc8816ce6e0d5f

test:
  secret_key_base: 0c2ebf5ca8f392d16908d912a788425c0728278693346c704d38e314f4d8b2492bf3e5ede625e03fcdeaa49ca05c61e1d0f35bf52430883c2bf10c4a1b38f2d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
